In [ ]:
import numpy as np
import pandas as pd
import random
import matplotlib.pyplot as plt
plt.style.use('seaborn')
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.feature_selection import SequentialFeatureSelector
from keras.models import Sequential
from keras.layers import Dense, Dropout
from sklearn.impute import SimpleImputer

<ipython-input-1-51f47998e7a3>:5: MatplotlibDeprecationWarning: The seaborn styles shipped by Matplotlib are deprecated since 3.6, as they no longer correspond to the styles shipped by seaborn. However, they will remain available as 'seaborn-v0_8-<style>'. Alternatively, directly use the seaborn API instead.
  plt.style.use('seaborn')

In [ ]:
data = {'A':[], 'B':[],'C':[],'D':[],'E':[],'F':[],'G':[]}

In [ ]:
for i in range(50):
    total = random.randint(100,1000)
    data['A'].append(0.20*total)
    data['B'].append(0.48*total)
    data['C'].append(0.24*total)
    data['D'].append(0.08*total)
    data['E'].append(0.05*total)
    data['F'].append(0.04*total)
    data['G'].append(total)

In [ ]:
df = pd.DataFrame(data)
df

        A       B       C      D      E      F    G
0   184.6  443.04  221.52  73.84  46.15  36.92  923
1   174.8  419.52  209.76  69.92  43.70  34.96  874
2    67.0  160.80   80.40  26.80  16.75  13.40  335
3   144.2  346.08  173.04  57.68  36.05  28.84  721
4    72.2  173.28   86.64  28.88  18.05  14.44  361
5    89.0  213.60  106.80  35.60  22.25  17.80  445
6    73.0  175.20   87.60  29.20  18.25  14.60  365
7   180.0  432.00  216.00  72.00  45.00  36.00  900
8    54.0  129.60   64.80  21.60  13.50  10.80  270
9   149.2  358.08  179.04  59.68  37.30  29.84  746
10  156.4  375.36  187.68  62.56  39.10  31.28  782
11  189.8  455.52  227.76  75.92  47.45  37.96  949
12   89.2  214.08  107.04  35.68  22.30  17.84  446
13  178.4  428.16  214.08  71.36  44.60  35.68  892
14  174.4  418.56  209.28  69.76  43.60  34.88  872
15  159.0  381.60  190.80  63.60  39.75  31.80  795
16  152.8  366.72  183.36  61.12  38.20  30.56  764
17   81.6  195.84   97.92  32.64  20.40  16.32  408
18   80.6  193.44   96.72  32.24  20.15  16.12  403
19   55.2  132.48   66.24  22.08  13.80  11.04  276
20  192.4  461.76  230.88  76.96  48.10  38.48  962
21  125.2  300.48  150.24  50.08  31.30  25.04  626
22  136.2  326.88  163.44  54.48  34.05  27.24  681
23   21.0   50.40   25.20   8.40   5.25   4.20  105
24   90.4  216.96  108.48  36.16  22.60  18.08  452
25  131.2  314.88  157.44  52.48  32.80  26.24  656
26  192.2  461.28  230.64  76.88  48.05  38.44  961
27  178.4  428.16  214.08  71.36  44.60  35.68  892
28   53.6  128.64   64.32  21.44  13.40  10.72  268
29  167.8  402.72  201.36  67.12  41.95  33.56  839
30  164.0  393.60  196.80  65.60  41.00  32.80  820
31  177.6  426.24  213.12  71.04  44.40  35.52  888
32  186.0  446.40  223.20  74.40  46.50  37.20  930
33  118.4  284.16  142.08  47.36  29.60  23.68  592
34  184.6  443.04  221.52  73.84  46.15  36.92  923
35  106.6  255.84  127.92  42.64  26.65  21.32  533
36  151.6  363.84  181.92  60.64  37.90  30.32  758
37  165.8  397.92  198.96  66.32  41.45  33.16  829
38   50.6  121.44   60.72  20.24  12.65  10.12  253
39  186.4  447.36  223.68  74.56  46.60  37.28  932
40  161.8  388.32  194.16  64.72  40.45  32.36  809
41   30.2   72.48   36.24  12.08   7.55   6.04  151
42  155.6  373.44  186.72  62.24  38.90  31.12  778
43  191.4  459.36  229.68  76.56  47.85  38.28  957
44  150.2  360.48  180.24  60.08  37.55  30.04  751
45   88.4  212.16  106.08  35.36  22.10  17.68  442
46   32.6   78.24   39.12  13.04   8.15   6.52  163
47   21.0   50.40   25.20   8.40   5.25   4.20  105
48   67.4  161.76   80.88  26.96  16.85  13.48  337
49  115.0  276.00  138.00  46.00  28.75  23.00  575

In [ ]:
df.to_csv('DL.csv')

In [ ]:
print('MAX A',df['A'].max())
print('MIN A :' ,df['A'].min())
print('MAX A',df['B'].max())
print('MIN A :' ,df['B'].min())

MAX A 192.4
MIN A : 21.0
MAX A 461.76
MIN A : 50.4

In [ ]:
df['class'] = 1

In [ ]:
# df['class'] = (df['A'] > df['A'].min()) & (df['A'] < df['A'].max()) & (df['B'] > df['B'].min()) & (df['B'] < df['B'].max())
li = ['A','B','C','D','E','F']
for i in li:
  df['class_'+i] =  (df[i] > df[i].min()) & (df[i] < df[i].max()) 
  df['class_'+i] = df['class_'+i].astype(int)
# del df['class']
df

,A,B,C,D,E,F,G,class_A,class_B,class_C,class_D,class_E,class_F
0,184.6,443.04,221.52,73.84,46.15,36.92,923,1,1,1,1,1,1
1,174.8,419.52,209.76,69.92,43.70,34.96,874,1,1,1,1,1,1
2,67.0,160.80,80.40,26.80,16.75,13.40,335,1,1,1,1,1,1
3,144.2,346.08,173.04,57.68,36.05,28.84,721,1,1,1,1,1,1
4,72.2,173.28,86.64,28.88,18.05,14.44,361,1,1,1,1,1,1
5,89.0,213.60,106.80,35.60,22.25,17.80,445,1,1,1,1,1,1
6,73.0,175.20,87.60,29.20,18.25,14.60,365,1,1,1,1,1,1
7,180.0,432.00,216.00,72.00,45.00,36.00,900,1,1,1,1,1,1
8,54.0,129.60,64.80,21.60,13.50,10.80,270,1,1,1,1,1,1
9,149.2,358.08,179.04,59.68,37.30,29.84,746,1,1,1,1,1,1
10,156.4,375.36,187.68,62.56,39.10,31.28,782,1,1,1,1,1,1
11,189.8,455.52,227.76,75.92,47.45,37.96,949,1,1,1,1,1,1
12,89.2,214.08,107.04,35.68,22.30,17.84,446,1,1,1,1,1,1
13,178.4,428.16,214.08,71.36,44.60,35.68,892,1,1,1,1,1,1
14,174.4,418.56,209.28,69.76,43.60,34.88,872,1,1,1,1,1,1
15,159.0,381.60,190.80,63.60,39.75,31.80,795,1,1,1,1,1,1
16,152.8,366.72,183.36,61.12,38.20,30.56,764,1,1,1,1,1,1
17,81.6,195.84,97.92,32.64,20.40,16.32,408,1,1,1,1,1,1
18,80.6,193.44,96.72,32.24,20.15,16.12,403,1,1,1,1,1,1
19,55.2,132.48,66.24,22.08,13.80,11.04,276,1,1,1,1,1,1
20,192.4,461.76,230.88,76.96,48.10,38.48,962,0,0,0,0,0,0
21,125.2,300.48,150.24,50.08,31.30,25.04,626,1,1,1,1,1,1
22,136.2,326.88,163.44,54.48,34.05,27.24,681,1,1,1,1,1,1
23,21.0,50.40,25.20,8.40,5.25,4.20,105,0,0,0,0,0,0
24,90.4,216.96,108.48,36.16,22.60,18.08,452,1,1,1,1,1,1
25,131.2,314.88,157.44,52.48,32.80,26.24,656,1,1,1,1,1,1
26,192.2,461.28,230.64,76.88,48.05,38.44,961,1,1,1,1,1,1
27,178.4,428.16,214.08,71.36,44.60,35.68,892,1,1,1,1,1,1
28,53.6,128.64,64.32,21.44,13.40,10.72,268,1,1,1,1,1,1
29,167.8,402.72,201.36,67.12,41.95,33.56,839,1,1,1,1,1,1
30,164.0,393.60,196.80,65.60,41.00,32.80,820,1,1,1,1,1,1
31,177.6,426.24,213.12,71.04,44.40,35.52,888,1,1,1,1,1,1
32,186.0,446.40,223.20,74.40,46.50,37.20,930,1,1,1,1,1,1
33,118.4,284.16,142.08,47.36,29.60,23.68,592,1,1,1,1,1,1
34,184.6,443.04,221.52,73.84,46.15,36.92,923,1,1,1,1,1,1
35,106.6,255.84,127.92,42.64,26.65,21.32,533,1,1,1,1,1,1
36,151.6,363.84,181.92,60.64,37.90,30.32,758,1,1,1,1,1,1
37,165.8,397.92,198.96,66.32,41.45,33.16,829,1,1,1,1,1,1
38,50.6,121.44,60.72,20.24,12.65,10.12,253,1,1,1,1,1,1
39,186.4,447.36,223.68,74.56,46.60,37.28,932,1,1,1,1,1,1
40,161.8,388.32,194.16,64.72,40.45,32.36,809,1,1,1,1,1,1
41,30.2,72.48,36.24,12.08,7.55,6.04,151,1,1,1,1,1,1
42,155.6,373.44,186.72,62.24,38.90,31.12,778,1,1,1,1,1,1
43,191.4,459.36,229.68,76.56,47.85,38.28,957,1,1,1,1,1,1
44,150.2,360.48,180.24,60.08,37.55,30.04,751,1,1,1,1,1,1
45,88.4,212.16,106.08,35.36,22.10,17.68,442,1,1,1,1,1,1
46,32.6,78.24,39.12,13.04,8.15,6.52,163,1,1,1,1,1,1
47,21.0,50.40,25.20,8.40,5.25,4.20,105,0,0,0,0,0,0
48,67.4,161.76,80.88,26.96,16.85,13.48,337,1,1,1,1,1,1
49,115.0,276.00,138.00,46.00,28.75,23.00,575,1,1,1,1,1,1

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import tree

In [ ]:
clfs = []
for i in li:
  y = df['class_'+i] 
  x = df.iloc[:, :-6]
  X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
  # print(x)
  # print(y)
  clf = tree.DecisionTreeClassifier()
  clf = clf.fit(X_train, y_train)
  y_pred = clf.predict(X_test)
  accuracy = accuracy_score(y_test, y_pred)
  print('Accuracy:', accuracy)
  clfs.append(clf)

Accuracy: 0.9
Accuracy: 0.9
Accuracy: 0.9
Accuracy: 0.9
Accuracy: 0.9
Accuracy: 0.9

In [ ]:
data = [[19,51,59,5,15,90,8]]
i = 0
for clf in clfs:
  print(li[i] ,clf.predict(data))
  i+=1

A [1]
B [0]
C [0]
D [0]
E [0]
F [1]

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(